import numpy as np

# Question 1
print("\n\n-------------- Question 01 --------------\n")
def generator_function():
    for i in range(10):
        yield i

gen = generator_function()
array = np.array([i for i in gen])
print("Array generated by the generator function:", array)

# Question 2
print("\n\n-------------- Question 02 --------------\n")
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))

are_equal = np.array_equal(A, B)
print("Are arrays A and B equal? ", are_equal)

# Question 3
print("\n\n-------------- Question 03 --------------\n")
vector = np.random.rand(100, 2)
distances = np.sqrt(np.sum((vector[:, None, :] - vector)**2, axis=-1))
print("Point by point distances: \n", distances)

# Question 4
print("\n\n-------------- Question 04 --------------\n")
matrix = np.random.rand(3, 3)
mean = np.mean(matrix, axis=1, keepdims=True)
matrix_mean_subtracted = matrix - mean
print("Mean subtracted matrix: \n", matrix_mean_subtracted)

# Question 5
print("\n\n-------------- Question 05 --------------\n")
array = np.array([[3, 2], [6, 5], [4, 8]])
nth_column = 1
sorted_array = array[array[:, nth_column].argsort()]
print("Sorted array by the {}th column: \n".format(nth_column), sorted_array)

# Question 6
print("\n\n-------------- Question 06 --------------\n")
matrix = np.random.rand(3, 3)
rank = np.linalg.matrix_rank(matrix)
print("Matrix rank: ", rank)

# Question 7
print("\n\n-------------- Question 07 --------------\n")
array = np.random.rand(16, 16)
block_size = (4, 4)
result = np.array([[np.sum(array[i:i+block_size[0], j:j+block_size[1]]) 
                   for j in range(0, array.shape[1], block_size[1])] 
                  for i in range(0, array.shape[0], block_size[0])])
print("Block-sum of the array: \n", result)
